// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/fwc-variants/Community.tsx": () => import("../components/mockups/fwc-variants/Community.tsx"),
  "./components/mockups/fwc-variants/Grounded.tsx": () => import("../components/mockups/fwc-variants/Grounded.tsx"),
  "./components/mockups/fwc-variants/Worth.tsx": () => import("../components/mockups/fwc-variants/Worth.tsx")
};
